filter:
  excluded_paths: [tests/*]

build:
  nodes:
    analysis:
      image: default-bionic
      dependencies:
        before:
          - sudo apt-get -y install libmagickwand-dev libmagickcore-dev
          - pecl install imagick
          - docker-php-ext-enable imagick
      environment:
        php:
          version: 8.0
          ini:
            "xdebug.mode": coverage,
            memory_limit: "-1"
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=coverage-file
            coverage:
              file: coverage-file
              format: php-clover
          - php-scrutinizer-run

checks:
  php:
    fix_doc_comments: true
