filter:
  excluded_paths: [tests/*]

build:
  nodes:
    analysis:
      image: default-bionic
      dependencies:
        before:
          - sudo apt-get -y install libmagickwand-dev libmagickcore-dev
          - printf "\n" | pecl install imagick
          - sed -i 's/extension="imagick.so"//g' `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
      environment:
        php:
          version: 8.0
          ini:
            "xdebug.mode": coverage,
            memory_limit: "-1"
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=coverage-file
            coverage:
              file: coverage-file
              format: php-clover
          - php-scrutinizer-run

checks:
  php:
    fix_doc_comments: true
